services:
  app:
    image: nginx:alpine
    container_name: ${PROJECT_NAME}-site
    volumes:
      - ./site:/usr/share/nginx/html:ro
    restart: unless-stopped
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${PROJECT_NAME}.rule=Host(`${PROJECT_NAME}.ibiete.cloud`)"
      - "traefik.http.routers.${PROJECT_NAME}.entrypoints=websecure"
      - "traefik.http.routers.${PROJECT_NAME}.tls=true"
      - "traefik.http.routers.${PROJECT_NAME}.tls.certresolver=letsencrypt"

networks:
  web:
    external: true
